server:
  port: 8118

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=appdb;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong@Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      mode: NEVER
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false
    defer-datasource-initialization: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: "0"
    baseline-description: "Initial baseline"
    validate-on-migrate: true
    locations:
      - classpath:db/migration